from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-image: url(images/pngwing.com (6).png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        self.start_menu = QtWidgets.QWidget()
        self.start_menu.setObjectName("start_menu")
        self.title = QtWidgets.QLabel(self.start_menu)
        self.title.setGeometry(QtCore.QRect(230, 80, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("background:transparent;")
        self.title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(self.start_menu)
        self.label_2.setGeometry(QtCore.QRect(260, 200, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.input_name = QtWidgets.QLineEdit(self.start_menu)
        self.input_name.setGeometry(QtCore.QRect(270, 290, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("background:none;")
        self.input_name.setObjectName("input_name")
        self.play_but = QtWidgets.QPushButton(self.start_menu)
        self.play_but.setGeometry(QtCore.QRect(320, 370, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(26)
        self.play_but.setFont(font)
        self.play_but.setStyleSheet("QPushButton {\n"
                                    "    border:none;\n"
                                    "    background:transparent;\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    color:white;\n"
                                    "}\n"
                                    "QPushButton:pressed {\n"
                                    "    color: rgb(214, 214, 214);\n"
                                    "}")
        self.play_but.setObjectName("play_but")
        self.stackedWidget.addWidget(self.start_menu)
        self.server_selection = QtWidgets.QWidget()
        self.server_selection.setObjectName("server_selection")
        self.label = QtWidgets.QLabel(self.server_selection)
        self.label.setGeometry(QtCore.QRect(270, 20, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;")
        self.label.setObjectName("label")
        self.server_list = QtWidgets.QListWidget(self.server_selection)
        self.server_list.setGeometry(QtCore.QRect(10, 70, 781, 271))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.server_list.setFont(font)
        self.server_list.setStyleSheet("QListWidget {\n"
                                       "        border:none;      \n"
                                       "        border-radius: 5px;          \n"
                                       "        font-size: 40px;\n"
                                       "        background: transparent;            \n"
                                       "    }\n"
                                       "    QListWidget::item {\n"
                                       "        padding: 10px;              \n"
                                       "    }\n"
                                       "    QListWidget::item:selected {\n"
                                       "        color: rgb(234, 234, 234);\n"
                                       "    }")
        self.server_list.setObjectName("server_list")
        self.label_3 = QtWidgets.QLabel(self.server_selection)
        self.label_3.setGeometry(QtCore.QRect(10, 400, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:transparent;")
        self.label_3.setObjectName("label_3")
        self.input_server = QtWidgets.QLineEdit(self.server_selection)
        self.input_server.setGeometry(QtCore.QRect(360, 400, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.input_server.setFont(font)
        self.input_server.setStyleSheet("background:none;")
        self.input_server.setObjectName("input_server")
        self.pushButton = QtWidgets.QPushButton(self.server_selection)
        self.pushButton.setGeometry(QtCore.QRect(90, 500, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    border:none;\n"
                                      "    background:transparent;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    color:white;\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    color: rgb(214, 214, 214);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.label_waiting = QtWidgets.QLabel(self.server_selection)
        self.label_waiting.setGeometry(QtCore.QRect(350, 490, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_waiting.setFont(font)
        self.label_waiting.setStyleSheet("background:transparent;")
        self.label_waiting.setText("")
        self.label_waiting.setObjectName("label_waiting")
        self.stackedWidget.addWidget(self.server_selection)
        self.game = QtWidgets.QWidget()
        self.game.setStyleSheet("background:transparent;")
        self.game.setObjectName("game")
        self.frame_field = QtWidgets.QFrame(self.game)
        self.frame_field.setGeometry(QtCore.QRect(50, 40, 661, 451))
        self.frame_field.setStyleSheet("QPushButton {\n"
                                       "    font-size: 84px;\n"
                                       "    font-weight: bold;\n"
                                       "}")
        self.frame_field.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_field.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_field.setObjectName("frame_field")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_field)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.field = QtWidgets.QGridLayout()
        self.field.setSpacing(0)
        self.field.setObjectName("field")
        self.frame_4 = QtWidgets.QFrame(self.frame_field)
        self.frame_4.setStyleSheet("border-right: 3px solid black;\n"
                                   "border-bottom: 3px solid black;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.field.addWidget(self.frame_4, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_field)
        self.frame_2.setStyleSheet("border-right: 3px solid black;\n"
                                   "border-bottom: 3px solid black;\n"
                                   "")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("border:none;")
        self.pushButton_2.setText("")
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.field.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_field)
        self.frame.setStyleSheet("border-right: 3px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_6.addWidget(self.pushButton_8)
        self.field.addWidget(self.frame, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_field)
        self.frame_3.setStyleSheet("border-right: 3px solid black;\n"
                                   "border-bottom: 3px solid black;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.field.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_field)
        self.frame_5.setStyleSheet("border-bottom: 3px solid black;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_5.addWidget(self.pushButton_7)
        self.field.addWidget(self.frame_5, 1, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_field)
        self.frame_6.setStyleSheet("border-right: 3px solid black;\n"
                                   "border-bottom: 3px solid black;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.field.addWidget(self.frame_6, 0, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_field)
        self.frame_7.setStyleSheet("border-bottom: 3px solid black;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.field.addWidget(self.frame_7, 0, 2, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_field)
        self.frame_8.setStyleSheet("border-right: 3px solid black;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_7.addWidget(self.pushButton_9)
        self.field.addWidget(self.frame_8, 2, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_field)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_8.addWidget(self.pushButton_10)
        self.field.addWidget(self.frame_9, 2, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.field)
        self.result_label = QtWidgets.QLabel(self.game)
        self.result_label.setGeometry(QtCore.QRect(50, 525, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(19)
        self.result_label.setFont(font)
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.buttons_after_game = QtWidgets.QFrame(self.game)
        self.buttons_after_game.setGeometry(QtCore.QRect(470, 500, 231, 89))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.buttons_after_game.setFont(font)
        self.buttons_after_game.setStyleSheet("QPushButton {\n"
                                              "    font-family: Monotype Corsiva;\n"
                                              "    font-size: 30px;\n"
                                              "}\n"
                                              "QPushButton:hover {\n"
                                              "    color: white;\n"
                                              "}\n"
                                              "QPushButton:pressed {\n"
                                              "    color: rgb(217, 217, 217);\n"
                                              "}")
        self.buttons_after_game.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_after_game.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_after_game.setObjectName("buttons_after_game")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.buttons_after_game)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.stackedWidget.addWidget(self.game)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Tic-tac-toe"))
        self.label_2.setText(_translate("MainWindow", "Enter your name:"))
        self.play_but.setText(_translate("MainWindow", "Play"))
        self.label.setText(_translate("MainWindow", "Server selection"))
        self.label_3.setText(_translate("MainWindow", "Enter the server address:"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
